"""
Generate source-free 1D Allen-Cahn data for blind inverse inference.

This script generates a clean numerical trajectory for the one-dimensional
Allen-Cahn equation:

    phi_t = -m_phi * mu

with chemical potential:

    mu = k * [ (1/eps) * (phi^3 - phi) - eps * phi_xx ]

and homogeneous Neumann boundary conditions:

    phi_x(0,t) = phi_x(1,t) = 0.

The data are generated by a classical method-of-lines discretization in space
and a stiff BDF solver in time. No manufactured source term is used. The true
mobility m_phi_true is used only to generate the trajectory and is saved for
final evaluation.

The generated dataset is intended for the source-free blind inverse benchmark,
where a PINN must infer m_phi from observations of phi(x,t).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Tuple

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import solve_ivp


# =============================================================================
# Default parameters
# =============================================================================

DEFAULT_M_PHI_TRUE = 0.1
DEFAULT_K = 1.0
DEFAULT_EPS = 0.08

DEFAULT_T_FINAL = 0.5
DEFAULT_N_X = 160
DEFAULT_N_SNAP = 101

DEFAULT_IC_A0 = 0.2
DEFAULT_IC_B0 = 0.3

DEFAULT_RTOL = 1e-9
DEFAULT_ATOL = 1e-11

DEFAULT_OUT_NPZ = "artifacts/ac1d_blind_data_mphi01.npz"
DEFAULT_OUT_PNG = "artifacts/ac1d_diagnostic_mphi01.png"
DEFAULT_OUT_JSON = "artifacts/ac1d_validation_mphi01.json"


# =============================================================================
# CLI
# =============================================================================

def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Generate source-free 1D Allen-Cahn data for blind inverse PINN tests."
    )

    # Physical parameters
    parser.add_argument(
        "--m_phi_true",
        type=float,
        default=DEFAULT_M_PHI_TRUE,
        help="True mobility used only to generate the numerical trajectory.",
    )
    parser.add_argument(
        "--k",
        type=float,
        default=DEFAULT_K,
        help="Surface-energy normalization constant in the chemical potential.",
    )
    parser.add_argument(
        "--eps",
        type=float,
        default=DEFAULT_EPS,
        help="Diffuse-interface width parameter.",
    )

    # Numerical setup
    parser.add_argument(
        "--t_final",
        type=float,
        default=DEFAULT_T_FINAL,
        help="Final simulation time.",
    )
    parser.add_argument(
        "--n_x",
        type=int,
        default=DEFAULT_N_X,
        help="Number of spatial grid points.",
    )
    parser.add_argument(
        "--n_snap",
        type=int,
        default=DEFAULT_N_SNAP,
        help="Number of saved time snapshots.",
    )

    # Initial condition
    parser.add_argument(
        "--ic_a0",
        type=float,
        default=DEFAULT_IC_A0,
        help="Mean value in the initial condition phi(x,0)=a0+b0*cos(pi*x).",
    )
    parser.add_argument(
        "--ic_b0",
        type=float,
        default=DEFAULT_IC_B0,
        help="Cosine amplitude in the initial condition phi(x,0)=a0+b0*cos(pi*x).",
    )

    # Solver tolerances
    parser.add_argument(
        "--rtol",
        type=float,
        default=DEFAULT_RTOL,
        help="Relative tolerance for solve_ivp.",
    )
    parser.add_argument(
        "--atol",
        type=float,
        default=DEFAULT_ATOL,
        help="Absolute tolerance for solve_ivp.",
    )

    # Validation thresholds
    parser.add_argument(
        "--grid_tol",
        type=float,
        default=1e-3,
        help="Tolerance for the coarse-vs-fine grid refinement check.",
    )
    parser.add_argument(
        "--energy_tol",
        type=float,
        default=1e-8,
        help="Allowed maximum positive energy increment.",
    )
    parser.add_argument(
        "--ls_tol",
        type=float,
        default=1e-2,
        help="Relative-error tolerance for weak/strong LS recovery checks.",
    )

    # Output files
    parser.add_argument(
        "--out_npz",
        type=str,
        default=DEFAULT_OUT_NPZ,
        help="Output NPZ dataset path.",
    )
    parser.add_argument(
        "--out_png",
        type=str,
        default=DEFAULT_OUT_PNG,
        help="Output diagnostic figure path.",
    )
    parser.add_argument(
        "--out_json",
        type=str,
        default=DEFAULT_OUT_JSON,
        help="Output validation JSON path.",
    )

    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    """
    Basic sanity checks on the input configuration.
    """
    if args.m_phi_true <= 0.0:
        raise ValueError("m_phi_true must be positive.")
    if args.k <= 0.0:
        raise ValueError("k must be positive.")
    if args.eps <= 0.0:
        raise ValueError("eps must be positive.")
    if args.t_final <= 0.0:
        raise ValueError("t_final must be positive.")
    if args.n_x < 3:
        raise ValueError("n_x must be at least 3.")
    if args.n_snap < 2:
        raise ValueError("n_snap must be at least 2.")
    if args.rtol <= 0.0 or args.atol <= 0.0:
        raise ValueError("rtol and atol must be positive.")


# =============================================================================
# Grid and discrete operators
# =============================================================================

def make_grid(n_x: int) -> Tuple[np.ndarray, float]:
    """
    Build a uniform grid on [0, 1].

    Parameters
    ----------
    n_x:
        Number of grid points.

    Returns
    -------
    x:
        Spatial grid.
    dx:
        Grid spacing.
    """
    x = np.linspace(0.0, 1.0, n_x)
    dx = x[1] - x[0]

    return x, dx


def trapezoid_weights(n_x: int, dx: float) -> np.ndarray:
    """
    Build trapezoidal quadrature weights for spatial integration.
    """
    weights = np.full(n_x, dx)
    weights[0] *= 0.5
    weights[-1] *= 0.5

    return weights


def laplacian_matrix(n_x: int, dx: float) -> np.ndarray:
    """
    Build the 1D second-derivative matrix with homogeneous Neumann BCs.

    Interior nodes:
        phi_xx[i] = (phi[i-1] - 2*phi[i] + phi[i+1]) / dx^2

    Boundary nodes use mirrored ghost points:
        phi[-1] = phi[1]
        phi[n]  = phi[n-2]

    This enforces zero normal derivative at both endpoints.
    """
    lap = np.zeros((n_x, n_x))

    for i in range(1, n_x - 1):
        lap[i, i - 1] = 1.0
        lap[i, i] = -2.0
        lap[i, i + 1] = 1.0

    lap[0, 0] = -2.0
    lap[0, 1] = 2.0

    lap[-1, -1] = -2.0
    lap[-1, -2] = 2.0

    return lap / dx**2


# =============================================================================
# Allen-Cahn model
# =============================================================================

def initial_condition(x: np.ndarray, ic_a0: float, ic_b0: float) -> np.ndarray:
    """
    Initial condition:
        phi(x,0) = ic_a0 + ic_b0*cos(pi*x).
    """
    return ic_a0 + ic_b0 * np.cos(np.pi * x)


def mu_of_phi(
    phi: np.ndarray,
    lap: np.ndarray,
    k: float,
    eps: float,
) -> np.ndarray:
    """
    Compute the discrete Allen-Cahn chemical potential.

    mu = k * [ (1/eps) * (phi^3 - phi) - eps * phi_xx ].
    """
    phi_xx = lap @ phi

    mu = k * (
        (1.0 / eps) * (phi**3 - phi)
        - eps * phi_xx
    )

    return mu


def rhs(
    time: float,
    phi: np.ndarray,
    lap: np.ndarray,
    m_phi: float,
    k: float,
    eps: float,
) -> np.ndarray:
    """
    Right-hand side of the semi-discrete Allen-Cahn ODE system.
    """
    return -m_phi * mu_of_phi(phi=phi, lap=lap, k=k, eps=eps)


def jacobian(
    time: float,
    phi: np.ndarray,
    lap: np.ndarray,
    m_phi: float,
    k: float,
    eps: float,
) -> np.ndarray:
    """
    Analytic Jacobian of the semi-discrete ODE right-hand side.

    Since:
        phi_t = -m_phi * mu(phi)

    and:
        dmu/dphi = k * [ (1/eps)*(3*phi^2 - 1)*I - eps*L ],

    then:
        d(phi_t)/dphi = -m_phi * dmu/dphi.
    """
    diag = k * (1.0 / eps) * (3.0 * phi**2 - 1.0)
    jac_mu = np.diag(diag) - k * eps * lap

    return -m_phi * jac_mu


# =============================================================================
# Energy and least-squares validation
# =============================================================================

def energy(
    phi: np.ndarray,
    dx: float,
    weights: np.ndarray,
    k: float,
    eps: float,
) -> float:
    """
    Compute the discrete Allen-Cahn energy:

        E = k * int [ eps/2 * phi_x^2 + (1/eps)*W(phi) ] dx

    with:
        W(phi) = 1/4 * (phi^2 - 1)^2.
    """
    phi_x_edges = (phi[1:] - phi[:-1]) / dx
    grad_term = 0.5 * eps * np.sum(phi_x_edges**2) * dx

    well = 0.25 * (phi**2 - 1.0) ** 2
    well_term = (1.0 / eps) * np.sum(weights * well)

    return float(k * (grad_term + well_term))


def weak_ls_estimate(
    phi_snaps: np.ndarray,
    t_snaps: np.ndarray,
    lap: np.ndarray,
    weights: np.ndarray,
    k: float,
    eps: float,
) -> float:
    """
    Weak-form least-squares estimate of m_phi from clean solver data.

    From:
        phi_t = -m_phi * mu,

    integrate between two consecutive snapshots:
        phi(t_b) - phi(t_a) = -m_phi * int_a^b mu dt.

    Therefore:
        A = int_a^b mu dt,
        B = -(phi(t_b) - phi(t_a)),

    and:
        m_phi = sum(w*A*B) / sum(w*A*A).
    """
    a_all = []
    b_all = []
    w_all = []

    for n in range(len(t_snaps) - 1):
        dt = t_snaps[n + 1] - t_snaps[n]

        mu_n = mu_of_phi(phi=phi_snaps[n], lap=lap, k=k, eps=eps)
        mu_np1 = mu_of_phi(phi=phi_snaps[n + 1], lap=lap, k=k, eps=eps)

        a = 0.5 * dt * (mu_n + mu_np1)
        b = -(phi_snaps[n + 1] - phi_snaps[n])

        a_all.append(a)
        b_all.append(b)
        w_all.append(weights)

    a_vec = np.concatenate(a_all)
    b_vec = np.concatenate(b_all)
    w_vec = np.concatenate(w_all)

    return float(np.sum(w_vec * a_vec * b_vec) / np.sum(w_vec * a_vec * a_vec))


def strong_ls_estimate(
    phi_snaps: np.ndarray,
    t_snaps: np.ndarray,
    lap: np.ndarray,
    weights: np.ndarray,
    k: float,
    eps: float,
) -> float:
    """
    Strong-form least-squares estimate of m_phi from clean solver data.

    From:
        -phi_t = m_phi * mu,

    therefore:
        m_phi = sum(w*mu*(-phi_t)) / sum(w*mu^2).

    The time derivative is approximated using centered finite differences.
    """
    a_all = []
    b_all = []
    w_all = []

    for n in range(1, len(t_snaps) - 1):
        dt_centered = t_snaps[n + 1] - t_snaps[n - 1]

        phi_t = (phi_snaps[n + 1] - phi_snaps[n - 1]) / dt_centered
        mu_n = mu_of_phi(phi=phi_snaps[n], lap=lap, k=k, eps=eps)

        a_all.append(mu_n)
        b_all.append(-phi_t)
        w_all.append(weights)

    a_vec = np.concatenate(a_all)
    b_vec = np.concatenate(b_all)
    w_vec = np.concatenate(w_all)

    return float(np.sum(w_vec * a_vec * b_vec) / np.sum(w_vec * a_vec * a_vec))


# =============================================================================
# Solver
# =============================================================================

def run_once(
    n_x: int,
    t_final: float,
    n_snap: int,
    m_phi_true: float,
    k: float,
    eps: float,
    ic_a0: float,
    ic_b0: float,
    rtol: float,
    atol: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, float, np.ndarray, np.ndarray]:
    """
    Solve the semi-discrete Allen-Cahn system for one spatial resolution.

    Returns
    -------
    x:
        Spatial grid.
    t_eval:
        Saved time snapshots.
    phi_snaps:
        Array of shape (n_snap, n_x).
    dx:
        Spatial grid spacing.
    lap:
        Neumann Laplacian matrix.
    weights:
        Trapezoidal integration weights.
    """
    x, dx = make_grid(n_x)
    weights = trapezoid_weights(n_x=n_x, dx=dx)
    lap = laplacian_matrix(n_x=n_x, dx=dx)

    phi0 = initial_condition(x=x, ic_a0=ic_a0, ic_b0=ic_b0)
    t_eval = np.linspace(0.0, t_final, n_snap)

    sol = solve_ivp(
        fun=rhs,
        t_span=(0.0, t_final),
        y0=phi0,
        method="BDF",
        t_eval=t_eval,
        jac=jacobian,
        args=(lap, m_phi_true, k, eps),
        rtol=rtol,
        atol=atol,
    )

    if not sol.success:
        raise RuntimeError(f"solve_ivp failed for n_x={n_x}: {sol.message}")

    phi_snaps = sol.y.T

    return x, t_eval, phi_snaps, dx, lap, weights


def l2_rel(a: np.ndarray, b: np.ndarray) -> float:
    """
    Relative Euclidean error between two arrays.
    """
    denom = np.linalg.norm(b)

    if denom == 0.0:
        return np.inf

    return float(np.linalg.norm(a - b) / denom)


# =============================================================================
# Validation checks
# =============================================================================

def validate_grid_refinement(args: argparse.Namespace) -> Dict[str, float | bool]:
    """
    Perform a simple grid-refinement check at final time.

    Coarse, medium and fine grids are chosen so that the fine solution can be
    compared to coarser grids by direct sub-sampling.
    """
    n0 = args.n_x

    _, _, phi_coarse, *_ = run_once(
        n_x=n0,
        t_final=args.t_final,
        n_snap=args.n_snap,
        m_phi_true=args.m_phi_true,
        k=args.k,
        eps=args.eps,
        ic_a0=args.ic_a0,
        ic_b0=args.ic_b0,
        rtol=args.rtol,
        atol=args.atol,
    )

    _, _, phi_medium, *_ = run_once(
        n_x=2 * n0 - 1,
        t_final=args.t_final,
        n_snap=args.n_snap,
        m_phi_true=args.m_phi_true,
        k=args.k,
        eps=args.eps,
        ic_a0=args.ic_a0,
        ic_b0=args.ic_b0,
        rtol=args.rtol,
        atol=args.atol,
    )

    _, _, phi_fine, *_ = run_once(
        n_x=4 * n0 - 3,
        t_final=args.t_final,
        n_snap=args.n_snap,
        m_phi_true=args.m_phi_true,
        k=args.k,
        eps=args.eps,
        ic_a0=args.ic_a0,
        ic_b0=args.ic_b0,
        rtol=args.rtol,
        atol=args.atol,
    )

    err_coarse = l2_rel(phi_coarse[-1], phi_fine[-1][::4])
    err_medium = l2_rel(phi_medium[-1], phi_fine[-1][::2])

    ratio = err_coarse / err_medium if err_medium > 0.0 else np.inf
    passed = err_coarse < args.grid_tol

    return {
        "err_coarse_vs_fine": float(err_coarse),
        "err_medium_vs_fine": float(err_medium),
        "error_ratio": float(ratio),
        "tolerance": float(args.grid_tol),
        "passed": bool(passed),
    }


def validate_energy_decay(
    phi: np.ndarray,
    dx: float,
    weights: np.ndarray,
    args: argparse.Namespace,
) -> Tuple[np.ndarray, Dict[str, float | bool]]:
    """
    Compute the energy trajectory and check monotonicity.
    """
    energies = np.array(
        [
            energy(
                phi=phi[n],
                dx=dx,
                weights=weights,
                k=args.k,
                eps=args.eps,
            )
            for n in range(phi.shape[0])
        ]
    )

    d_energy = np.diff(energies)
    max_increase = float(d_energy.max())
    passed = max_increase <= args.energy_tol

    summary = {
        "energy_initial": float(energies[0]),
        "energy_final": float(energies[-1]),
        "max_energy_increment": max_increase,
        "tolerance": float(args.energy_tol),
        "passed": bool(passed),
    }

    return energies, summary


def validate_ls_recovery(
    phi: np.ndarray,
    t: np.ndarray,
    lap: np.ndarray,
    weights: np.ndarray,
    args: argparse.Namespace,
) -> Dict[str, float | bool]:
    """
    Check direct weak/strong least-squares recovery on clean solver data.

    This is an oracle validation check. It verifies that the clean full-grid
    trajectory contains enough information to recover the true mobility.
    """
    m_weak = weak_ls_estimate(
        phi_snaps=phi,
        t_snaps=t,
        lap=lap,
        weights=weights,
        k=args.k,
        eps=args.eps,
    )

    m_strong = strong_ls_estimate(
        phi_snaps=phi,
        t_snaps=t,
        lap=lap,
        weights=weights,
        k=args.k,
        eps=args.eps,
    )

    err_weak = abs(m_weak - args.m_phi_true) / abs(args.m_phi_true)
    err_strong = abs(m_strong - args.m_phi_true) / abs(args.m_phi_true)

    passed = (err_weak < args.ls_tol) and (err_strong < args.ls_tol)

    return {
        "m_phi_true": float(args.m_phi_true),
        "m_phi_weak_ls": float(m_weak),
        "m_phi_strong_ls": float(m_strong),
        "rel_error_weak": float(err_weak),
        "rel_error_strong": float(err_strong),
        "tolerance": float(args.ls_tol),
        "passed": bool(passed),
    }


# =============================================================================
# Plotting and saving
# =============================================================================

def make_figure(
    x: np.ndarray,
    t: np.ndarray,
    phi: np.ndarray,
    energies: np.ndarray,
    out_png: Path,
) -> None:
    """
    Create a diagnostic figure with profiles, space-time map and energy decay.
    """
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.2))

    profile_indices = [
        0,
        len(t) // 4,
        len(t) // 2,
        3 * len(t) // 4,
        len(t) - 1,
    ]

    for idx in profile_indices:
        axes[0].plot(x, phi[idx], label=f"t={t[idx]:.2f}")

    axes[0].set_title(r"$\phi(x,t)$ profiles")
    axes[0].set_xlabel("x")
    axes[0].set_ylabel(r"$\phi$")
    axes[0].axhline(1.0, linestyle=":", linewidth=0.8)
    axes[0].axhline(-1.0, linestyle=":", linewidth=0.8)
    axes[0].legend(fontsize=8)

    image = axes[1].imshow(
        phi,
        aspect="auto",
        origin="lower",
        extent=[x[0], x[-1], t[0], t[-1]],
        vmin=-1.0,
        vmax=1.0,
    )

    axes[1].set_title(r"$\phi(x,t)$")
    axes[1].set_xlabel("x")
    axes[1].set_ylabel("t")

    fig.colorbar(image, ax=axes[1], fraction=0.046)

    axes[2].plot(t, energies, "-o", markersize=3)
    axes[2].set_title("Energy decay")
    axes[2].set_xlabel("t")
    axes[2].set_ylabel("E")

    fig.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=130)
    plt.close(fig)


def save_dataset(
    out_npz: Path,
    x: np.ndarray,
    t: np.ndarray,
    phi: np.ndarray,
    dx: float,
    energies: np.ndarray,
    args: argparse.Namespace,
) -> None:
    """
    Save the generated AC1D dataset to NPZ.
    """
    out_npz.parent.mkdir(parents=True, exist_ok=True)

    np.savez(
        out_npz,
        x=x,
        t=t,
        phi=phi,
        m_phi_true=args.m_phi_true,
        k=args.k,
        eps=args.eps,
        dx=dx,
        ic_a0=args.ic_a0,
        ic_b0=args.ic_b0,
        energy=energies,
    )


def save_validation_json(
    out_json: Path,
    args: argparse.Namespace,
    validation: Dict[str, object],
) -> None:
    """
    Save configuration and validation diagnostics to JSON.
    """
    out_json.parent.mkdir(parents=True, exist_ok=True)

    output = {
        "configuration": {
            "m_phi_true": args.m_phi_true,
            "k": args.k,
            "eps": args.eps,
            "t_final": args.t_final,
            "n_x": args.n_x,
            "n_snap": args.n_snap,
            "ic_a0": args.ic_a0,
            "ic_b0": args.ic_b0,
            "rtol": args.rtol,
            "atol": args.atol,
            "out_npz": args.out_npz,
            "out_png": args.out_png,
        },
        "validation": validation,
    }

    with open(out_json, "w") as f:
        json.dump(output, f, indent=4)


# =============================================================================
# Main
# =============================================================================

def main() -> bool:
    """
    Generate the dataset, validate it, and save outputs.
    """
    args = parse_args()
    validate_args(args)

    out_npz = Path(args.out_npz)
    out_png = Path(args.out_png)
    out_json = Path(args.out_json)

    print("=" * 80)
    print("AC1D SOURCE-FREE DATA GENERATION")
    print("=" * 80)
    print(f"m_phi_true = {args.m_phi_true}")
    print(f"k          = {args.k}")
    print(f"eps        = {args.eps}")
    print(f"T_final    = {args.t_final}")
    print(f"N_x        = {args.n_x}")
    print(f"N_snap     = {args.n_snap}")
    print("=" * 80)

    # -------------------------------------------------------------------------
    # Main simulation
    # -------------------------------------------------------------------------
    x, t, phi, dx, lap, weights = run_once(
        n_x=args.n_x,
        t_final=args.t_final,
        n_snap=args.n_snap,
        m_phi_true=args.m_phi_true,
        k=args.k,
        eps=args.eps,
        ic_a0=args.ic_a0,
        ic_b0=args.ic_b0,
        rtol=args.rtol,
        atol=args.atol,
    )

    print("Main simulation completed.")
    print(f"phi shape : {phi.shape}")
    print(f"phi(t=0) : min={phi[0].min():+.6f} | max={phi[0].max():+.6f}")
    print(f"phi(t=T) : min={phi[-1].min():+.6f} | max={phi[-1].max():+.6f}")

    # -------------------------------------------------------------------------
    # Validation A: grid refinement
    # -------------------------------------------------------------------------
    print("-" * 80)
    print("(A) Grid refinement check")

    grid_summary = validate_grid_refinement(args)

    print(f"relative L2 error | coarse vs fine : {grid_summary['err_coarse_vs_fine']:.6e}")
    print(f"relative L2 error | medium vs fine : {grid_summary['err_medium_vs_fine']:.6e}")
    print(f"error ratio       | expected ~4    : {grid_summary['error_ratio']:.3f}")
    print(f"grid check passed                  : {grid_summary['passed']}")

    # -------------------------------------------------------------------------
    # Validation B: energy monotonicity
    # -------------------------------------------------------------------------
    print("-" * 80)
    print("(B) Energy monotonicity check")

    energies, energy_summary = validate_energy_decay(
        phi=phi,
        dx=dx,
        weights=weights,
        args=args,
    )

    print(f"E(0)                      : {energy_summary['energy_initial']:.8e}")
    print(f"E(T)                      : {energy_summary['energy_final']:.8e}")
    print(f"max energy increment       : {energy_summary['max_energy_increment']:.8e}")
    print(f"energy monotonicity passed : {energy_summary['passed']}")

    # -------------------------------------------------------------------------
    # Validation C: direct m_phi recovery on clean solver data
    # -------------------------------------------------------------------------
    print("-" * 80)
    print("(C) Least-squares recovery check")

    ls_summary = validate_ls_recovery(
        phi=phi,
        t=t,
        lap=lap,
        weights=weights,
        args=args,
    )

    print(f"m_phi_true      : {ls_summary['m_phi_true']:.8e}")
    print(
        f"m_phi_weak_ls   : {ls_summary['m_phi_weak_ls']:.8e} | "
        f"rel.err={ls_summary['rel_error_weak']:.8e}"
    )
    print(
        f"m_phi_strong_ls : {ls_summary['m_phi_strong_ls']:.8e} | "
        f"rel.err={ls_summary['rel_error_strong']:.8e}"
    )
    print(f"recovery passed : {ls_summary['passed']}")

    # -------------------------------------------------------------------------
    # Final summary
    # -------------------------------------------------------------------------
    validation = {
        "grid_refinement": grid_summary,
        "energy_decay": energy_summary,
        "least_squares_recovery": ls_summary,
    }

    all_ok = (
        bool(grid_summary["passed"])
        and bool(energy_summary["passed"])
        and bool(ls_summary["passed"])
    )

    validation["all_checks_passed"] = bool(all_ok)

    print("=" * 80)
    print("VALIDATION SUMMARY")
    print(f"grid refinement : {grid_summary['passed']}")
    print(f"energy decay    : {energy_summary['passed']}")
    print(f"LS recovery     : {ls_summary['passed']}")
    print(f"all checks      : {all_ok}")
    print("=" * 80)

    # -------------------------------------------------------------------------
    # Save dataset, figure and validation report
    # -------------------------------------------------------------------------
    save_dataset(
        out_npz=out_npz,
        x=x,
        t=t,
        phi=phi,
        dx=dx,
        energies=energies,
        args=args,
    )

    make_figure(
        x=x,
        t=t,
        phi=phi,
        energies=energies,
        out_png=out_png,
    )

    save_validation_json(
        out_json=out_json,
        args=args,
        validation=validation,
    )

    print(f"Saved data              : {out_npz}")
    print(f"Saved diagnostic figure : {out_png}")
    print(f"Saved validation JSON   : {out_json}")

    return bool(all_ok)


if __name__ == "__main__":
    main()