"""
Run AC1D blind inverse training across multiple random seeds.

This script launches train_inverse_ac1d.py several times with identical
experimental settings and different seeds. Each seed changes all stochastic
components of the training pipeline:

1. Network initialization.
2. Observed data subset when data_fraction < 1.
3. Gaussian noise realization when data_noise > 0.
4. Stochastic batches used during optimization.

Per-seed metrics are read from:

    <out_root>/<run_name>_seed<seed>/metrics.json

and aggregated into:

    <out_root>/<run_name>_multiseed.json

The summary reports mean, sample standard deviation and raw values for each
tracked metric.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np


METRIC_KEYS = [
    "m_phi_final",
    "m_phi_relative_error",
    "full_grid_mse_phi",
    "full_grid_relative_l2_phi",
]


# =============================================================================
# CLI
# =============================================================================

def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Run AC1D blind inverse training over multiple seeds."
    )

    # -------------------------------------------------------------------------
    # Data and output
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--data_path",
        type=str,
        required=True,
        help="Path to the .npz dataset generated by generate_ac1d_data.py.",
    )
    parser.add_argument(
        "--run_name",
        type=str,
        required=True,
        help="Base run name. Per-seed runs are named <run_name>_seed<seed>.",
    )
    parser.add_argument(
        "--out_root",
        type=str,
        default="artifacts",
        help="Root directory used by the training script and summary output.",
    )
    parser.add_argument(
        "--seeds",
        type=int,
        nargs="+",
        default=[0, 1, 2, 3, 4],
        help="Random seeds to run.",
    )
    parser.add_argument(
        "--train_script",
        type=str,
        default="train_inverse_ac1d.py",
        help="Training script to launch for each seed.",
    )

    # -------------------------------------------------------------------------
    # Experiment definition
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--data_fraction",
        type=float,
        default=1.0,
        help="Observed data fraction passed to the training script.",
    )
    parser.add_argument(
        "--data_noise",
        type=float,
        default=0.0,
        help="Relative data noise passed to the training script.",
    )

    # -------------------------------------------------------------------------
    # Training passthrough options
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--epochs",
        type=int,
        default=5000,
        help="Adam inverse-training epochs per seed.",
    )
    parser.add_argument(
        "--pretrain_epochs",
        type=int,
        default=1000,
        help="Pretraining epochs per seed.",
    )
    parser.add_argument(
        "--lbfgs_iter",
        type=int,
        default=0,
        help="Optional L-BFGS iterations per seed.",
    )
    parser.add_argument(
        "--m_phi_init",
        type=float,
        default=0.2,
        help="Initial guess for m_phi passed to the training script.",
    )
    parser.add_argument(
        "--hidden_layers",
        type=int,
        default=4,
        help="Number of hidden layers passed to the training script.",
    )
    parser.add_argument(
        "--hidden_dim",
        type=int,
        default=128,
        help="Hidden dimension passed to the training script.",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Network learning rate passed to the training script.",
    )
    parser.add_argument(
        "--m_phi_lr",
        type=float,
        default=5e-3,
        help="log_m_phi learning rate passed to the training script.",
    )

    # -------------------------------------------------------------------------
    # Batch sizes
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--n_data",
        type=int,
        default=10000,
        help="Number of supervised data points per batch.",
    )
    parser.add_argument(
        "--n_pde",
        type=int,
        default=10000,
        help="Number of PDE collocation points per batch.",
    )
    parser.add_argument(
        "--n_ic",
        type=int,
        default=1000,
        help="Number of initial-condition points per batch.",
    )
    parser.add_argument(
        "--n_bc",
        type=int,
        default=1000,
        help="Number of boundary-condition points per batch.",
    )

    # -------------------------------------------------------------------------
    # Loss weights
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--data_weight",
        type=float,
        default=10.0,
        help="Data-loss weight passed to the training script.",
    )
    parser.add_argument(
        "--pde_weight",
        type=float,
        default=1.0,
        help="PDE-loss weight passed to the training script.",
    )
    parser.add_argument(
        "--ic_weight",
        type=float,
        default=10.0,
        help="Initial-condition loss weight passed to the training script.",
    )
    parser.add_argument(
        "--bc_weight",
        type=float,
        default=1.0,
        help="Boundary-condition loss weight passed to the training script.",
    )

    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    """
    Basic sanity checks for the multi-seed configuration.
    """
    if len(args.seeds) == 0:
        raise ValueError("At least one seed must be provided.")
    if not (0.0 < args.data_fraction <= 1.0):
        raise ValueError("data_fraction must be in (0, 1].")
    if args.data_noise < 0.0:
        raise ValueError("data_noise must be non-negative.")
    if args.epochs < 0:
        raise ValueError("epochs must be non-negative.")
    if args.pretrain_epochs < 0:
        raise ValueError("pretrain_epochs must be non-negative.")
    if args.lbfgs_iter < 0:
        raise ValueError("lbfgs_iter must be non-negative.")
    if args.m_phi_init <= 0.0:
        raise ValueError("m_phi_init must be positive.")


# =============================================================================
# Single-seed execution
# =============================================================================

def build_train_command(args: argparse.Namespace, seed: int, run_name: str) -> List[str]:
    """
    Build the subprocess command for one seed.
    """
    return [
        sys.executable,
        args.train_script,
        "--data_path",
        args.data_path,
        "--run_name",
        run_name,
        "--out_root",
        args.out_root,
        "--seed",
        str(seed),
        "--data_fraction",
        str(args.data_fraction),
        "--data_noise",
        str(args.data_noise),
        "--epochs",
        str(args.epochs),
        "--pretrain_epochs",
        str(args.pretrain_epochs),
        "--lbfgs_iter",
        str(args.lbfgs_iter),
        "--m_phi_init",
        str(args.m_phi_init),
        "--hidden_layers",
        str(args.hidden_layers),
        "--hidden_dim",
        str(args.hidden_dim),
        "--lr",
        str(args.lr),
        "--m_phi_lr",
        str(args.m_phi_lr),
        "--n_data",
        str(args.n_data),
        "--n_pde",
        str(args.n_pde),
        "--n_ic",
        str(args.n_ic),
        "--n_bc",
        str(args.n_bc),
        "--data_weight",
        str(args.data_weight),
        "--pde_weight",
        str(args.pde_weight),
        "--ic_weight",
        str(args.ic_weight),
        "--bc_weight",
        str(args.bc_weight),
    ]


def load_metrics(metrics_path: Path) -> Dict[str, Any]:
    """
    Load metrics.json from one training run.
    """
    if not metrics_path.exists():
        raise FileNotFoundError(f"Missing metrics file: {metrics_path}")

    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    missing = [key for key in METRIC_KEYS if key not in metrics]

    if missing:
        raise KeyError(f"Missing metric keys in {metrics_path}: {missing}")

    return metrics


def run_one_seed(args: argparse.Namespace, seed: int) -> Dict[str, Any]:
    """
    Launch the training script for one seed and return its metrics.
    """
    seed_run_name = f"{args.run_name}_seed{seed}"

    command = build_train_command(
        args=args,
        seed=seed,
        run_name=seed_run_name,
    )

    print("=" * 80)
    print(f"SEED {seed} ({seed_run_name})")
    print("=" * 80)
    print("Command:")
    print(" ".join(command))
    print("=" * 80)

    subprocess.run(command, check=True)

    metrics_path = Path(args.out_root) / seed_run_name / "metrics.json"
    metrics = load_metrics(metrics_path)

    metrics["seed"] = seed
    metrics["run_name"] = seed_run_name

    return metrics


# =============================================================================
# Aggregation
# =============================================================================

def aggregate(records: List[Dict[str, Any]], metric_keys: List[str]) -> Dict[str, Any]:
    """
    Compute mean, sample standard deviation and raw values for each metric.
    """
    summary = {}

    for key in metric_keys:
        values = np.array([record[key] for record in records], dtype=np.float64)

        summary[key] = {
            "mean": float(values.mean()),
            "std": float(values.std(ddof=1)) if len(values) > 1 else 0.0,
            "values": values.tolist(),
        }

    return summary


def build_output(
    args: argparse.Namespace,
    records: List[Dict[str, Any]],
    summary: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Build the JSON-serializable multi-seed output.
    """
    return {
        "run_name": args.run_name,
        "out_root": args.out_root,
        "train_script": args.train_script,
        "seeds": args.seeds,
        "experiment": {
            "data_path": args.data_path,
            "data_fraction": args.data_fraction,
            "data_noise": args.data_noise,
            "epochs": args.epochs,
            "pretrain_epochs": args.pretrain_epochs,
            "lbfgs_iter": args.lbfgs_iter,
            "m_phi_init": args.m_phi_init,
            "hidden_layers": args.hidden_layers,
            "hidden_dim": args.hidden_dim,
            "lr": args.lr,
            "m_phi_lr": args.m_phi_lr,
            "n_data": args.n_data,
            "n_pde": args.n_pde,
            "n_ic": args.n_ic,
            "n_bc": args.n_bc,
            "data_weight": args.data_weight,
            "pde_weight": args.pde_weight,
            "ic_weight": args.ic_weight,
            "bc_weight": args.bc_weight,
        },
        "metric_keys": METRIC_KEYS,
        "per_seed_records": records,
        "summary": summary,
    }


def print_summary(args: argparse.Namespace, summary: Dict[str, Any]) -> None:
    """
    Print the multi-seed summary.
    """
    print("\n" + "=" * 80)
    print("MULTI-SEED SUMMARY")
    print("=" * 80)
    print(f"run_name      : {args.run_name}")
    print(f"out_root      : {args.out_root}")
    print(f"seeds         : {args.seeds}")
    print(f"data_fraction : {args.data_fraction}")
    print(f"data_noise    : {args.data_noise}")
    print("-" * 80)

    for key in METRIC_KEYS:
        item = summary[key]
        print(f"{key:28s} : {item['mean']:.6e} +/- {item['std']:.2e}")

    print("=" * 80)


def save_summary(output: Dict[str, Any], out_path: Path) -> None:
    """
    Save the multi-seed summary JSON.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with open(out_path, "w") as f:
        json.dump(output, f, indent=4)

    print(f"Saved summary to: {out_path}")


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    """
    Run all seeds and aggregate metrics.
    """
    args = parse_args()
    validate_args(args)

    records = []

    for seed in args.seeds:
        records.append(run_one_seed(args, seed))

    summary = aggregate(
        records=records,
        metric_keys=METRIC_KEYS,
    )

    print_summary(
        args=args,
        summary=summary,
    )

    output = build_output(
        args=args,
        records=records,
        summary=summary,
    )

    out_path = Path(args.out_root) / f"{args.run_name}_multiseed.json"

    save_summary(
        output=output,
        out_path=out_path,
    )


if __name__ == "__main__":
    main()