"""
train_inverse_ac1d.py
======================================================================
Minimal PINN benchmark for blind inverse inference of m_phi in 1D
source-free Allen-Cahn dynamics.

We train a neural network phi_theta(x,t) on numerical data generated by
generate_ac1d_data.py. The inverse problem is genuinely blind because:

    - no manufactured source term is used;
    - m_phi_true appears only in the saved dataset for final comparison;
    - the training loss uses only phi observations and the source-free PDE.

Model:
    phi_t + m_phi * mu(phi) = 0

with:
    mu(phi) = k * [ (1/eps)(phi^3 - phi) - eps * phi_xx ]

The unknown parameter is constrained positive via:
    m_phi = exp(log_m_phi)
"""

import argparse
import json
import math
from pathlib import Path

import numpy as np

import torch
from torch import nn
from torch.optim import Adam

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from model import SimpleAC1D


# ---------------------------------------------------------------------
# 1. CLI
# ---------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser()

    # data / output
    parser.add_argument("--data_path", type=str, required=True)
    parser.add_argument("--run_name", type=str, required=True)
    # parser.add_argument("--out_root", type=str, default="artifacts/")
    parser.add_argument("--seed", type=int, default=1234)

    # model
    parser.add_argument("--hidden_layers", type=int, default=4)
    parser.add_argument("--hidden_dim", type=int, default=128)

    # training
    parser.add_argument("--epochs", type=int, default=5000)
    parser.add_argument("--pretrain_epochs", type=int, default=1000)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--m_phi_lr", type=float, default=5e-3)
    parser.add_argument("--lbfgs_iter", type=int, default=0)
    parser.add_argument("--print_every", type=int, default=100)

    # inverse parameter
    parser.add_argument("--m_phi_init", type=float, default=0.2)

    # sampling
    parser.add_argument("--n_data", type=int, default=10000)
    parser.add_argument("--n_pde", type=int, default=10000)
    parser.add_argument("--n_ic", type=int, default=1000)
    parser.add_argument("--n_bc", type=int, default=1000)

    # observed-data degradation
    parser.add_argument("--data_fraction", type=float, default=1.0)
    parser.add_argument("--data_noise", type=float, default=0.0)

    # loss weights
    parser.add_argument("--data_weight", type=float, default=10.0)
    parser.add_argument("--pde_weight", type=float, default=1.0)
    parser.add_argument("--ic_weight", type=float, default=10.0)
    parser.add_argument("--bc_weight", type=float, default=1.0)

    return parser.parse_args()


# ---------------------------------------------------------------------
# 3. Autograd helpers and physics
# ---------------------------------------------------------------------

def grad(u, z):
    return torch.autograd.grad(
        u,
        z,
        grad_outputs=torch.ones_like(u),
        create_graph=True,
        retain_graph=True,
    )[0]


def mu_from_phi(phi, x, k: float, eps: float):
    """
    mu(phi) = k * [ (1/eps)(phi^3 - phi) - eps * phi_xx ]
    """
    phi_x = grad(phi, x)
    phi_xx = grad(phi_x, x)

    mu = k * ((phi**3 - phi) / eps - eps * phi_xx)
    return mu


# ---------------------------------------------------------------------
# 4. Dataset loading
# ---------------------------------------------------------------------

def load_ac1d_data(args, device):
    """
    Load .npz generated by generate_ac1d_data.py.

    Expected keys:
        x, t, phi, m_phi_true, k, eps, ic_a0, ic_b0

    phi is expected with shape [n_t, n_x].
    """

    data_npz = np.load(args.data_path)

    x_grid = data_npz["x"].astype(np.float32)
    t_grid = data_npz["t"].astype(np.float32)
    phi_grid = data_npz["phi"].astype(np.float32)

    m_phi_true = float(data_npz["m_phi_true"])
    k = float(data_npz["k"])
    eps = float(data_npz["eps"])

    ic_a0 = float(data_npz["ic_a0"]) if "ic_a0" in data_npz else None
    ic_b0 = float(data_npz["ic_b0"]) if "ic_b0" in data_npz else None

    if phi_grid.shape != (len(t_grid), len(x_grid)):
        raise ValueError(
            f"Expected phi shape {(len(t_grid), len(x_grid))}, got {phi_grid.shape}"
        )

    t_final = float(t_grid[-1])

    # Build flattened supervised dataset: (x_i, t_n, phi_n_i)
    X = np.tile(x_grid[None, :], (len(t_grid), 1))
    T = np.tile(t_grid[:, None], (1, len(x_grid)))

    x_all = torch.tensor(X.reshape(-1, 1), dtype=torch.float32, device=device)
    t_all = torch.tensor(T.reshape(-1, 1), dtype=torch.float32, device=device)
    phi_clean_all = torch.tensor(phi_grid.reshape(-1, 1), dtype=torch.float32, device=device)

    # Add fixed relative Gaussian noise once, if requested.
    phi_obs_all = phi_clean_all.clone()
    if args.data_noise > 0.0:
        gen = torch.Generator(device=device)
        gen.manual_seed(args.seed + 1000)

        scale = torch.std(phi_clean_all)
        noise = torch.randn(
            phi_clean_all.shape,
            generator=gen,
            device=device,
            dtype=phi_clean_all.dtype,
        )
        phi_obs_all = phi_clean_all + args.data_noise * scale * noise

    # Select a fixed observed subset.
    if not (0.0 < args.data_fraction <= 1.0):
        raise ValueError("--data_fraction must be in (0, 1].")

    n_total = x_all.shape[0]
    n_obs = max(1, int(round(args.data_fraction * n_total)))

    rng = np.random.default_rng(args.seed)
    obs_idx_np = rng.choice(n_total, size=n_obs, replace=False)
    obs_idx = torch.tensor(obs_idx_np, dtype=torch.long, device=device)

    data = {
        # tensors for training
        "x_obs": x_all[obs_idx],
        "t_obs": t_all[obs_idx],
        "phi_obs": phi_obs_all[obs_idx],

        # full tensors for evaluation
        "x_all": x_all,
        "t_all": t_all,
        "phi_clean_all": phi_clean_all,

        # numpy arrays for plotting
        "x_grid": x_grid,
        "t_grid": t_grid,
        "phi_grid": phi_grid,

        # constants
        "m_phi_true": m_phi_true,
        "k": k,
        "eps": eps,
        "ic_a0": ic_a0,
        "ic_b0": ic_b0,
        "t_final": t_final,
        "n_total": n_total,
        "n_obs": n_obs,
    }

    return data


# ---------------------------------------------------------------------
# 5. Sampling
# ---------------------------------------------------------------------

def sample_data_batch(data, n_data: int, gen):
    """
    Sample observed points from the fixed observed dataset.
    Sampling is with replacement.
    """
    x_obs = data["x_obs"]
    t_obs = data["t_obs"]
    phi_obs = data["phi_obs"]

    n_obs = x_obs.shape[0]

    if n_data <= 0:
        return x_obs, t_obs, phi_obs

    idx = torch.randint(
        low=0,
        high=n_obs,
        size=(n_data,),
        device=x_obs.device,
        generator=gen,
    )

    return x_obs[idx], t_obs[idx], phi_obs[idx]


def sample_batches(data, args, device, gen):
    """
    Create one stochastic batch for data, PDE, IC and BC losses.
    """

    # supervised data
    x_data, t_data, phi_data = sample_data_batch(data, args.n_data, gen)

    # PDE collocation points in [0,1] x [0,T]
    x_pde = torch.rand((args.n_pde, 1), device=device, generator=gen)
    t_pde = torch.rand((args.n_pde, 1), device=device, generator=gen) * data["t_final"]

    # IC points: t = 0
    x_ic = torch.rand((args.n_ic, 1), device=device, generator=gen)
    t_ic = torch.zeros_like(x_ic)

    # BC points: x = 0 and x = 1
    n_half = max(1, args.n_bc // 2)

    t_bc_left = torch.rand((n_half, 1), device=device, generator=gen) * data["t_final"]
    t_bc_right = torch.rand((n_half, 1), device=device, generator=gen) * data["t_final"]

    x_bc_left = torch.zeros_like(t_bc_left)
    x_bc_right = torch.ones_like(t_bc_right)

    return {
        "x_data": x_data,
        "t_data": t_data,
        "phi_data": phi_data,

        "x_pde": x_pde,
        "t_pde": t_pde,

        "x_ic": x_ic,
        "t_ic": t_ic,

        "x_bc_left": x_bc_left,
        "t_bc_left": t_bc_left,
        "x_bc_right": x_bc_right,
        "t_bc_right": t_bc_right,
    }


# ---------------------------------------------------------------------
# 6. Loss evaluation
# ---------------------------------------------------------------------

def true_ic(x, data):
    """
    Exact initial condition used by generate_ac1d_data.py:
        phi(x,0) = ic_a0 + ic_b0*cos(pi*x)
    """
    if data["ic_a0"] is None or data["ic_b0"] is None:
        raise ValueError("ic_a0/ic_b0 not found in dataset.")

    return data["ic_a0"] + data["ic_b0"] * torch.cos(math.pi * x)


def evaluate_losses(model, log_m_phi, batch, data, args, use_pde: bool):
    """
    Compute all losses from one fixed batch.

    Important:
    x_pde, t_pde and boundary x tensors are cloned with requires_grad=True
    because PDE and BC losses need derivatives w.r.t. inputs.
    """

    m_phi = torch.exp(log_m_phi)

    # -------------------------
    # Data loss
    # -------------------------
    phi_pred_data = model(batch["x_data"], batch["t_data"])
    loss_data = torch.mean((phi_pred_data - batch["phi_data"]) ** 2)

    # -------------------------
    # IC loss
    # -------------------------
    phi_pred_ic = model(batch["x_ic"], batch["t_ic"])
    phi_true_ic = true_ic(batch["x_ic"], data)
    loss_ic = torch.mean((phi_pred_ic - phi_true_ic) ** 2)

    # -------------------------
    # BC loss: phi_x(0,t)=0 and phi_x(1,t)=0
    # -------------------------
    x_left = batch["x_bc_left"].detach().clone().requires_grad_(True)
    t_left = batch["t_bc_left"].detach().clone()

    x_right = batch["x_bc_right"].detach().clone().requires_grad_(True)
    t_right = batch["t_bc_right"].detach().clone()

    phi_left = model(x_left, t_left)
    phi_right = model(x_right, t_right)

    phi_x_left = grad(phi_left, x_left)
    phi_x_right = grad(phi_right, x_right)

    loss_bc = torch.mean(phi_x_left ** 2) + torch.mean(phi_x_right ** 2)

    # -------------------------
    # PDE loss
    # -------------------------
    if use_pde:
        x_pde = batch["x_pde"].detach().clone().requires_grad_(True)
        t_pde = batch["t_pde"].detach().clone().requires_grad_(True)

        phi_pde = model(x_pde, t_pde)
        phi_t = grad(phi_pde, t_pde)

        mu_pde = mu_from_phi(
            phi=phi_pde,
            x=x_pde,
            k=data["k"],
            eps=data["eps"],
        )

        residual = phi_t + m_phi * mu_pde
        loss_pde = torch.mean(residual ** 2)
    else:
        loss_pde = torch.zeros((), device=batch["x_data"].device)

    total = (
        args.data_weight * loss_data
        + args.ic_weight * loss_ic
        + args.bc_weight * loss_bc
        + args.pde_weight * loss_pde
    )

    losses = {
        "total": total,
        "data": loss_data,
        "ic": loss_ic,
        "bc": loss_bc,
        "pde": loss_pde,
        "m_phi": m_phi,
    }

    return total, losses


# ---------------------------------------------------------------------
# 7. Plotting and saving
# ---------------------------------------------------------------------

def save_config(args, data, run_dir):
    config = vars(args).copy()
    config.update(
        {
            "m_phi_true": data["m_phi_true"],
            "k": data["k"],
            "eps": data["eps"],
            "t_final": data["t_final"],
            "n_total_data_points": data["n_total"],
            "n_observed_data_points": data["n_obs"],
        }
    )

    with open(run_dir / "run_config.json", "w") as f:
        json.dump(config, f, indent=4)


def append_history(history, losses):
    for key in ["total", "data", "ic", "bc", "pde", "m_phi"]:
        history[key].append(float(losses[key].detach().cpu()))


def plot_losses(history, fig_dir):
    fig_dir.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 5))

    for key in ["total", "data", "pde", "ic", "bc"]:
        values = np.array(history[key], dtype=np.float64)
        values = np.maximum(values, 1e-16)
        plt.semilogy(values, label=key)

    plt.xlabel("Optimization step")
    plt.ylabel("Loss")
    plt.title("AC1D blind inverse training losses")
    plt.legend()
    plt.grid(True, which="both", linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.savefig(fig_dir / "losses.png", dpi=180)
    plt.close()


def plot_m_phi(history, data, fig_dir):
    plt.figure(figsize=(8, 5))

    m_vals = np.array(history["m_phi"], dtype=np.float64)
    plt.plot(m_vals, label=r"learned $m_\phi$")
    plt.axhline(data["m_phi_true"], linestyle="--", color="black", label=r"true $m_\phi$")

    plt.xlabel("Optimization step")
    plt.ylabel(r"$m_\phi$")
    plt.title("Blind inverse inference of mobility")
    plt.legend()
    plt.grid(True, alpha=0.4)
    plt.tight_layout()
    plt.savefig(fig_dir / "m_phi_convergence.png", dpi=180)
    plt.close()


def evaluate_on_full_grid(model, data):
    model.eval()

    with torch.no_grad():
        phi_pred = model(data["x_all"], data["t_all"])

    phi_true = data["phi_clean_all"]

    mse = torch.mean((phi_pred - phi_true) ** 2)
    rel_l2 = torch.linalg.norm(phi_pred - phi_true) / torch.linalg.norm(phi_true)

    n_t = len(data["t_grid"])
    n_x = len(data["x_grid"])

    phi_pred_grid = phi_pred.detach().cpu().numpy().reshape(n_t, n_x)

    return {
        "mse": float(mse.detach().cpu()),
        "rel_l2": float(rel_l2.detach().cpu()),
        "phi_pred_grid": phi_pred_grid,
    }


def plot_field_diagnostics(eval_results, data, fig_dir):
    x = data["x_grid"]
    t = data["t_grid"]
    phi_true = data["phi_grid"]
    phi_pred = eval_results["phi_pred_grid"]
    err = np.abs(phi_pred - phi_true)

    # final-time comparison
    plt.figure(figsize=(7, 4.5))
    plt.plot(x, phi_true[-1], label="solver data")
    plt.plot(x, phi_pred[-1], "--", label="PINN")
    plt.xlabel("x")
    plt.ylabel(r"$\phi(x,T)$")
    plt.title("Final-time profile")
    plt.legend()
    plt.grid(True, alpha=0.4)
    plt.tight_layout()
    plt.savefig(fig_dir / "phi_final_comparison.png", dpi=180)
    plt.close()

    # error heatmap
    plt.figure(figsize=(7, 4.5))
    plt.imshow(
        err,
        aspect="auto",
        origin="lower",
        extent=[x[0], x[-1], t[0], t[-1]],
    )
    plt.colorbar(label=r"$|\phi_\theta-\phi_{data}|$")
    plt.xlabel("x")
    plt.ylabel("t")
    plt.title("Absolute error heatmap")
    plt.tight_layout()
    plt.savefig(fig_dir / "phi_error_heatmap.png", dpi=180)
    plt.close()


def save_metrics(metrics, out_path):
    clean_metrics = {}
    for key, value in metrics.items():
        if isinstance(value, (float, int, str, bool)):
            clean_metrics[key] = value

    with open(out_path, "w") as f:
        json.dump(clean_metrics, f, indent=4)


# ---------------------------------------------------------------------
# 8. Main training
# ---------------------------------------------------------------------

def main():
    args = parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    run_dir = Path("artifacts") / args.run_name
    fig_dir = run_dir / "figures"
    weights_dir = run_dir / "weights"

    fig_dir.mkdir(parents=True, exist_ok=True)
    weights_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("AC1D BLIND INVERSE PINN")
    print("=" * 80)
    print(f"Device      : {device}")
    print(f"Data path   : {args.data_path}")
    print(f"Run dir     : {run_dir}")
    print(f"m_phi_init  : {args.m_phi_init}")
    print("=" * 80)

    data = load_ac1d_data(args, device)

    print("Loaded data:")
    print(f"  m_phi_true        = {data['m_phi_true']:.6f}")
    print(f"  k                 = {data['k']:.6f}")
    print(f"  eps               = {data['eps']:.6f}")
    print(f"  T_final           = {data['t_final']:.6f}")
    print(f"  total data points = {data['n_total']}")
    print(f"  observed points   = {data['n_obs']}")
    print(f"  data_fraction     = {args.data_fraction}")
    print(f"  data_noise        = {args.data_noise}")
    print("=" * 80)

    save_config(args, data, run_dir)

    model = SimpleAC1D(
        hidden_layers=args.hidden_layers,
        hidden_dim=args.hidden_dim
    ).to(device)

    log_m_phi = nn.Parameter(
        torch.tensor(math.log(args.m_phi_init), dtype=torch.float32, device=device)
    )

    optimizer = Adam(
        [
            {"params": model.parameters(), "lr": args.lr},
            {"params": [log_m_phi], "lr": args.m_phi_lr},
        ]
    )

    gen = torch.Generator(device=device)
    gen.manual_seed(args.seed + 2000)

    history = {
        "total": [],
        "data": [],
        "ic": [],
        "bc": [],
        "pde": [],
        "m_phi": [],
    }

    # ------------------------------------------------------------
    # Phase 1: pretraining without PDE
    # ------------------------------------------------------------
    if args.pretrain_epochs > 0:
        print("\n" + "=" * 40)
        print("PRETRAIN: data + IC + BC only")
        print("=" * 40)

        for epoch in range(1, args.pretrain_epochs + 1):
            model.train()
            batch = sample_batches(data, args, device, gen)

            optimizer.zero_grad()
            total, losses = evaluate_losses(
                model=model,
                log_m_phi=log_m_phi,
                batch=batch,
                data=data,
                args=args,
                use_pde=False,
            )
            total.backward()
            optimizer.step()

            append_history(history, losses)

            if epoch == 1 or epoch % args.print_every == 0:
                print(
                    f"Pretrain {epoch:05d} | "
                    f"Total: {losses['total'].item():.4e} | "
                    f"Data: {losses['data'].item():.4e} | "
                    f"IC: {losses['ic'].item():.4e} | "
                    f"BC: {losses['bc'].item():.4e} | "
                    f"m_phi: {losses['m_phi'].item():.6e}"
                )

    # ------------------------------------------------------------
    # Phase 2: inverse training with PDE
    # ------------------------------------------------------------
    print("\n" + "=" * 40)
    print("ADAM INVERSE TRAINING")
    print("=" * 40)

    for epoch in range(1, args.epochs + 1):
        model.train()
        batch = sample_batches(data, args, device, gen)

        optimizer.zero_grad()
        total, losses = evaluate_losses(
            model=model,
            log_m_phi=log_m_phi,
            batch=batch,
            data=data,
            args=args,
            use_pde=True,
        )
        total.backward()
        optimizer.step()

        append_history(history, losses)

        if epoch == 1 or epoch % args.print_every == 0:
            rel_err = abs(losses["m_phi"].item() - data["m_phi_true"]) / abs(data["m_phi_true"])
            print(
                f"Epoch {epoch:05d} | "
                f"Total: {losses['total'].item():.4e} | "
                f"Data: {losses['data'].item():.4e} | "
                f"PDE: {losses['pde'].item():.4e} | "
                f"IC: {losses['ic'].item():.4e} | "
                f"BC: {losses['bc'].item():.4e} | "
                f"m_phi: {losses['m_phi'].item():.6e} | "
                f"rel.err: {rel_err:.3e}"
            )

    # ------------------------------------------------------------
    # Optional L-BFGS refinement on one fixed batch
    # ------------------------------------------------------------
    if args.lbfgs_iter > 0:
        print("\n" + "=" * 40)
        print("L-BFGS REFINEMENT")
        print("=" * 40)

        fixed_batch = sample_batches(data, args, device, gen)

        lbfgs = torch.optim.LBFGS(
            list(model.parameters()) + [log_m_phi],
            lr=1.0,
            max_iter=args.lbfgs_iter,
            max_eval=args.lbfgs_iter * 2,
            history_size=50,
            tolerance_grad=1e-10,
            tolerance_change=1e-12,
            line_search_fn="strong_wolfe",
        )

        def closure():
            lbfgs.zero_grad()

            total, losses = evaluate_losses(
                model=model,
                log_m_phi=log_m_phi,
                batch=fixed_batch,
                data=data,
                args=args,
                use_pde=True,
            )

            total.backward()
            append_history(history, losses)
            return total

        lbfgs.step(closure)

        with torch.no_grad():
            final_m = torch.exp(log_m_phi).item()
        print(f"L-BFGS completed | m_phi = {final_m:.8e}")

    # ------------------------------------------------------------
    # Save final artifacts
    # ------------------------------------------------------------
    torch.save(model.state_dict(), weights_dir / "model.pt")

    with torch.no_grad():
        final_m_phi = float(torch.exp(log_m_phi).detach().cpu())

    eval_results = evaluate_on_full_grid(model, data)

    rel_m_phi_error = abs(final_m_phi - data["m_phi_true"]) / abs(data["m_phi_true"])

    metrics = {
        "m_phi_true": data["m_phi_true"],
        "m_phi_final": final_m_phi,
        "m_phi_relative_error": rel_m_phi_error,
        "full_grid_mse_phi": eval_results["mse"],
        "full_grid_relative_l2_phi": eval_results["rel_l2"],
        "data_fraction": args.data_fraction,
        "data_noise": args.data_noise,
        "n_observed_data_points": data["n_obs"],
    }

    save_metrics(metrics, run_dir / "metrics.json")

    plot_losses(history, fig_dir)
    plot_m_phi(history, data, fig_dir)
    plot_field_diagnostics(eval_results, data, fig_dir)

    print("\n" + "=" * 80)
    print("FINAL RESULTS")
    print("=" * 80)
    print(f"m_phi_true             : {data['m_phi_true']:.8e}")
    print(f"m_phi_final            : {final_m_phi:.8e}")
    print(f"m_phi_relative_error   : {rel_m_phi_error:.8e}")
    print(f"full_grid_mse_phi      : {eval_results['mse']:.8e}")
    print(f"full_grid_rel_l2_phi   : {eval_results['rel_l2']:.8e}")
    print(f"Saved run to           : {run_dir}")
    print("=" * 80)


if __name__ == "__main__":
    main()