"""
Train a source-free 1D Allen-Cahn PINN for blind inverse inference of m_phi.

The network predicts only the physical phase field:

    (x, t) -> phi_theta(x, t)

The chemical potential is computed from phi_theta by automatic differentiation:

    mu_theta = k * [ (1/eps) * (phi_theta^3 - phi_theta)
                    - eps * phi_theta_xx ]

The inverse parameter is the mobility m_phi in:

    phi_t + m_phi * mu = 0

and is constrained to be positive through:

    m_phi = exp(log_m_phi)

The benchmark is source-free: no manufactured source term is used during
training. The true value m_phi_true appears only in the generated dataset and is
used here only for final diagnostics and reporting.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, Tuple

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import torch
from torch import Tensor, nn
from torch.optim import Adam

from model import SimpleAC1D


# =============================================================================
# CLI
# =============================================================================

def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Train a source-free AC1D inverse PINN for m_phi inference."
    )

    # -------------------------------------------------------------------------
    # Data and output
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--data_path",
        type=str,
        required=True,
        help="Path to the .npz dataset generated by generate_ac1d_data.py.",
    )
    parser.add_argument(
        "--run_name",
        type=str,
        required=True,
        help="Name of the training run.",
    )
    parser.add_argument(
        "--out_root",
        type=str,
        default="artifacts",
        help="Root directory for run artifacts.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=1234,
        help="Random seed for initialization, data subsampling and noise.",
    )

    # -------------------------------------------------------------------------
    # Model
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--hidden_layers",
        type=int,
        default=4,
        help="Number of hidden layers in the MLP.",
    )
    parser.add_argument(
        "--hidden_dim",
        type=int,
        default=128,
        help="Number of neurons in each hidden layer.",
    )

    # -------------------------------------------------------------------------
    # Optimization
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--epochs",
        type=int,
        default=5000,
        help="Number of Adam inverse-training epochs with the PDE loss active.",
    )
    parser.add_argument(
        "--pretrain_epochs",
        type=int,
        default=1000,
        help="Number of pretraining epochs without the PDE loss.",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Adam learning rate for network parameters.",
    )
    parser.add_argument(
        "--m_phi_lr",
        type=float,
        default=5e-3,
        help="Adam learning rate for log_m_phi.",
    )
    parser.add_argument(
        "--lbfgs_iter",
        type=int,
        default=0,
        help="Optional number of L-BFGS refinement iterations. Use 0 to disable.",
    )
    parser.add_argument(
        "--print_every",
        type=int,
        default=100,
        help="Logging frequency in optimization steps.",
    )

    # -------------------------------------------------------------------------
    # Inverse parameter
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--m_phi_init",
        type=float,
        default=0.2,
        help="Initial guess for m_phi. The optimized variable is log(m_phi).",
    )

    # -------------------------------------------------------------------------
    # Sampling
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--n_data",
        type=int,
        default=10000,
        help="Number of observed data points sampled per batch. If <=0, all observed points are used.",
    )
    parser.add_argument(
        "--n_pde",
        type=int,
        default=10000,
        help="Number of PDE collocation points per batch.",
    )
    parser.add_argument(
        "--n_ic",
        type=int,
        default=1000,
        help="Number of initial-condition points per batch.",
    )
    parser.add_argument(
        "--n_bc",
        type=int,
        default=1000,
        help="Number of boundary-condition points per batch.",
    )

    # -------------------------------------------------------------------------
    # Observed-data degradation
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--data_fraction",
        type=float,
        default=1.0,
        help="Fraction of the full solver grid retained as observed data.",
    )
    parser.add_argument(
        "--data_noise",
        type=float,
        default=0.0,
        help="Relative Gaussian noise level added once to the observed phi data.",
    )

    # -------------------------------------------------------------------------
    # Loss weights
    # -------------------------------------------------------------------------
    parser.add_argument(
        "--data_weight",
        type=float,
        default=10.0,
        help="Weight of the supervised data loss.",
    )
    parser.add_argument(
        "--pde_weight",
        type=float,
        default=1.0,
        help="Weight of the source-free PDE residual loss.",
    )
    parser.add_argument(
        "--ic_weight",
        type=float,
        default=10.0,
        help="Weight of the initial-condition loss.",
    )
    parser.add_argument(
        "--bc_weight",
        type=float,
        default=1.0,
        help="Weight of the homogeneous Neumann boundary loss.",
    )

    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    """
    Basic sanity checks on the training configuration.
    """
    if args.hidden_layers < 1:
        raise ValueError("hidden_layers must be at least 1.")
    if args.hidden_dim <= 0:
        raise ValueError("hidden_dim must be positive.")
    if args.epochs < 0:
        raise ValueError("epochs must be non-negative.")
    if args.pretrain_epochs < 0:
        raise ValueError("pretrain_epochs must be non-negative.")
    if args.lr <= 0.0:
        raise ValueError("lr must be positive.")
    if args.m_phi_lr <= 0.0:
        raise ValueError("m_phi_lr must be positive.")
    if args.lbfgs_iter < 0:
        raise ValueError("lbfgs_iter must be non-negative.")
    if args.print_every <= 0:
        raise ValueError("print_every must be positive.")
    if args.m_phi_init <= 0.0:
        raise ValueError("m_phi_init must be positive because log(m_phi_init) is used.")
    if args.n_pde <= 0:
        raise ValueError("n_pde must be positive.")
    if args.n_ic <= 0:
        raise ValueError("n_ic must be positive.")
    if args.n_bc <= 0:
        raise ValueError("n_bc must be positive.")
    if not (0.0 < args.data_fraction <= 1.0):
        raise ValueError("data_fraction must be in (0, 1].")
    if args.data_noise < 0.0:
        raise ValueError("data_noise must be non-negative.")


# =============================================================================
# Autograd helpers and physics
# =============================================================================

def grad(u: Tensor, z: Tensor) -> Tensor:
    """
    Compute du/dz using PyTorch autograd.
    """
    return torch.autograd.grad(
        u,
        z,
        grad_outputs=torch.ones_like(u),
        create_graph=True,
        retain_graph=True,
    )[0]


def mu_from_phi(
    phi: Tensor,
    x: Tensor,
    k: float,
    eps: float,
) -> Tensor:
    """
    Compute the Allen-Cahn chemical potential from phi_theta:

        mu = k * [ (1/eps)(phi^3 - phi) - eps * phi_xx ].
    """
    phi_x = grad(phi, x)
    phi_xx = grad(phi_x, x)

    mu = k * ((phi**3 - phi) / eps - eps * phi_xx)

    return mu


# =============================================================================
# Dataset loading
# =============================================================================

def load_ac1d_data(args: argparse.Namespace, device: torch.device) -> Dict[str, Any]:
    """
    Load an AC1D dataset generated by generate_ac1d_data.py.

    Expected NPZ keys
    -----------------
    x, t, phi, m_phi_true, k, eps, ic_a0, ic_b0

    Notes
    -----
    phi is expected with shape (n_t, n_x). The supervised dataset is built by
    flattening the full space-time solver grid.

    Data degradation is applied once at loading time:
    - data_fraction selects a fixed random observed subset;
    - data_noise adds fixed relative Gaussian noise to the full phi field before
      the observed subset is extracted.
    """
    data_npz = np.load(args.data_path)

    x_grid = data_npz["x"].astype(np.float32)
    t_grid = data_npz["t"].astype(np.float32)
    phi_grid = data_npz["phi"].astype(np.float32)

    m_phi_true = float(data_npz["m_phi_true"])
    k = float(data_npz["k"])
    eps = float(data_npz["eps"])

    ic_a0 = float(data_npz["ic_a0"]) if "ic_a0" in data_npz else None
    ic_b0 = float(data_npz["ic_b0"]) if "ic_b0" in data_npz else None

    expected_shape = (len(t_grid), len(x_grid))

    if phi_grid.shape != expected_shape:
        raise ValueError(f"Expected phi shape {expected_shape}, got {phi_grid.shape}.")

    t_final = float(t_grid[-1])

    x_mesh = np.tile(x_grid[None, :], (len(t_grid), 1))
    t_mesh = np.tile(t_grid[:, None], (1, len(x_grid)))

    x_all = torch.tensor(
        x_mesh.reshape(-1, 1),
        dtype=torch.float32,
        device=device,
    )
    t_all = torch.tensor(
        t_mesh.reshape(-1, 1),
        dtype=torch.float32,
        device=device,
    )
    phi_clean_all = torch.tensor(
        phi_grid.reshape(-1, 1),
        dtype=torch.float32,
        device=device,
    )

    phi_obs_all = phi_clean_all.clone()

    if args.data_noise > 0.0:
        generator = torch.Generator(device=device)
        generator.manual_seed(args.seed + 1000)

        scale = torch.std(phi_clean_all)

        noise = torch.randn(
            phi_clean_all.shape,
            generator=generator,
            device=device,
            dtype=phi_clean_all.dtype,
        )

        phi_obs_all = phi_clean_all + args.data_noise * scale * noise

    n_total = x_all.shape[0]
    n_obs = max(1, int(round(args.data_fraction * n_total)))

    rng = np.random.default_rng(args.seed)
    obs_idx_np = rng.choice(n_total, size=n_obs, replace=False)
    obs_idx = torch.tensor(obs_idx_np, dtype=torch.long, device=device)

    data = {
        # Observed tensors for training.
        "x_obs": x_all[obs_idx],
        "t_obs": t_all[obs_idx],
        "phi_obs": phi_obs_all[obs_idx],
        # Full clean tensors for final evaluation.
        "x_all": x_all,
        "t_all": t_all,
        "phi_clean_all": phi_clean_all,
        # NumPy arrays for plotting.
        "x_grid": x_grid,
        "t_grid": t_grid,
        "phi_grid": phi_grid,
        # Physical and dataset metadata.
        "m_phi_true": m_phi_true,
        "k": k,
        "eps": eps,
        "ic_a0": ic_a0,
        "ic_b0": ic_b0,
        "t_final": t_final,
        "n_total": int(n_total),
        "n_obs": int(n_obs),
    }

    return data


# =============================================================================
# Sampling
# =============================================================================

def sample_data_batch(
    data: Dict[str, Any],
    n_data: int,
    generator: torch.Generator,
) -> Tuple[Tensor, Tensor, Tensor]:
    """
    Sample observed data points from the fixed observed subset.

    Sampling is with replacement. If n_data <= 0, all observed points are used.
    """
    x_obs = data["x_obs"]
    t_obs = data["t_obs"]
    phi_obs = data["phi_obs"]

    n_obs = x_obs.shape[0]

    if n_data <= 0:
        return x_obs, t_obs, phi_obs

    idx = torch.randint(
        low=0,
        high=n_obs,
        size=(n_data,),
        device=x_obs.device,
        generator=generator,
    )

    return x_obs[idx], t_obs[idx], phi_obs[idx]


def sample_batches(
    data: Dict[str, Any],
    args: argparse.Namespace,
    device: torch.device,
    generator: torch.Generator,
) -> Dict[str, Tensor]:
    """
    Sample one stochastic batch for data, PDE, IC and BC losses.
    """
    x_data, t_data, phi_data = sample_data_batch(
        data=data,
        n_data=args.n_data,
        generator=generator,
    )

    x_pde = torch.rand((args.n_pde, 1), device=device, generator=generator)
    t_pde = torch.rand((args.n_pde, 1), device=device, generator=generator) * data["t_final"]

    x_ic = torch.rand((args.n_ic, 1), device=device, generator=generator)
    t_ic = torch.zeros_like(x_ic)

    n_half = max(1, args.n_bc // 2)

    t_bc_left = torch.rand((n_half, 1), device=device, generator=generator) * data["t_final"]
    t_bc_right = torch.rand((n_half, 1), device=device, generator=generator) * data["t_final"]

    x_bc_left = torch.zeros_like(t_bc_left)
    x_bc_right = torch.ones_like(t_bc_right)

    return {
        "x_data": x_data,
        "t_data": t_data,
        "phi_data": phi_data,
        "x_pde": x_pde,
        "t_pde": t_pde,
        "x_ic": x_ic,
        "t_ic": t_ic,
        "x_bc_left": x_bc_left,
        "t_bc_left": t_bc_left,
        "x_bc_right": x_bc_right,
        "t_bc_right": t_bc_right,
    }


# =============================================================================
# Loss evaluation
# =============================================================================

def true_initial_condition(x: Tensor, data: Dict[str, Any]) -> Tensor:
    """
    Exact initial condition used by generate_ac1d_data.py:

        phi(x,0) = ic_a0 + ic_b0*cos(pi*x).
    """
    if data["ic_a0"] is None or data["ic_b0"] is None:
        raise ValueError("ic_a0/ic_b0 not found in dataset.")

    return data["ic_a0"] + data["ic_b0"] * torch.cos(math.pi * x)


def evaluate_losses(
    model: nn.Module,
    log_m_phi: nn.Parameter,
    batch: Dict[str, Tensor],
    data: Dict[str, Any],
    args: argparse.Namespace,
    use_pde: bool,
) -> Tuple[Tensor, Dict[str, Tensor]]:
    """
    Evaluate the composite PINN loss on one fixed batch.

    Loss terms
    ----------
    1. Data loss:
       MSE between phi_theta and observed phi data.

    2. Initial-condition loss:
       MSE against the analytic initial condition.

    3. Boundary-condition loss:
       homogeneous Neumann condition phi_x(0,t)=phi_x(1,t)=0.

    4. PDE loss:
       source-free Allen-Cahn residual
           R = phi_t + m_phi * mu_theta.

    During pretraining, use_pde=False and the PDE term is set to zero.
    """
    m_phi = torch.exp(log_m_phi)

    # -------------------------------------------------------------------------
    # Supervised data loss
    # -------------------------------------------------------------------------
    phi_pred_data = model(batch["x_data"], batch["t_data"])
    loss_data = torch.mean((phi_pred_data - batch["phi_data"]) ** 2)

    # -------------------------------------------------------------------------
    # Initial-condition loss
    # -------------------------------------------------------------------------
    phi_pred_ic = model(batch["x_ic"], batch["t_ic"])
    phi_true_ic = true_initial_condition(batch["x_ic"], data)
    loss_ic = torch.mean((phi_pred_ic - phi_true_ic) ** 2)

    # -------------------------------------------------------------------------
    # Boundary loss: phi_x(0,t)=0 and phi_x(1,t)=0
    # -------------------------------------------------------------------------
    x_left = batch["x_bc_left"].detach().clone().requires_grad_(True)
    t_left = batch["t_bc_left"].detach().clone()

    x_right = batch["x_bc_right"].detach().clone().requires_grad_(True)
    t_right = batch["t_bc_right"].detach().clone()

    phi_left = model(x_left, t_left)
    phi_right = model(x_right, t_right)

    phi_x_left = grad(phi_left, x_left)
    phi_x_right = grad(phi_right, x_right)

    loss_bc = torch.mean(phi_x_left**2) + torch.mean(phi_x_right**2)

    # -------------------------------------------------------------------------
    # Source-free PDE residual loss
    # -------------------------------------------------------------------------
    if use_pde:
        x_pde = batch["x_pde"].detach().clone().requires_grad_(True)
        t_pde = batch["t_pde"].detach().clone().requires_grad_(True)

        phi_pde = model(x_pde, t_pde)
        phi_t = grad(phi_pde, t_pde)

        mu_pde = mu_from_phi(
            phi=phi_pde,
            x=x_pde,
            k=data["k"],
            eps=data["eps"],
        )

        residual = phi_t + m_phi * mu_pde
        loss_pde = torch.mean(residual**2)
    else:
        loss_pde = torch.zeros((), device=batch["x_data"].device)

    total = (
        args.data_weight * loss_data
        + args.ic_weight * loss_ic
        + args.bc_weight * loss_bc
        + args.pde_weight * loss_pde
    )

    losses = {
        "total": total,
        "data": loss_data,
        "ic": loss_ic,
        "bc": loss_bc,
        "pde": loss_pde,
        "m_phi": m_phi,
    }

    return total, losses


# =============================================================================
# Training helpers
# =============================================================================

def initialize_model_and_optimizer(
    args: argparse.Namespace,
    device: torch.device,
) -> Tuple[nn.Module, nn.Parameter, torch.optim.Optimizer]:
    """
    Initialize the PINN, log_m_phi and Adam optimizer.
    """
    model = SimpleAC1D(
        hidden_layers=args.hidden_layers,
        hidden_dim=args.hidden_dim,
    ).to(device)

    log_m_phi = nn.Parameter(
        torch.tensor(
            math.log(args.m_phi_init),
            dtype=torch.float32,
            device=device,
        )
    )

    optimizer = Adam(
        [
            {"params": model.parameters(), "lr": args.lr},
            {"params": [log_m_phi], "lr": args.m_phi_lr},
        ]
    )

    return model, log_m_phi, optimizer


def init_history() -> Dict[str, list]:
    """
    Initialize training history.
    """
    return {
        "total": [],
        "data": [],
        "ic": [],
        "bc": [],
        "pde": [],
        "m_phi": [],
        "phase": [],
    }


def append_history(
    history: Dict[str, list],
    losses: Dict[str, Tensor],
    phase: str,
) -> None:
    """
    Append one optimization step to the training history.
    """
    for key in ["total", "data", "ic", "bc", "pde", "m_phi"]:
        history[key].append(float(losses[key].detach().cpu()))

    history["phase"].append(phase)


def print_step(
    prefix: str,
    step: int,
    losses: Dict[str, Tensor],
    m_phi_true: float,
    include_pde: bool,
) -> None:
    """
    Print one training step in a compact format.
    """
    rel_err = abs(losses["m_phi"].item() - m_phi_true) / abs(m_phi_true)

    msg = (
        f"{prefix} {step:05d} | "
        f"Total: {losses['total'].item():.4e} | "
        f"Data: {losses['data'].item():.4e} | "
    )

    if include_pde:
        msg += f"PDE: {losses['pde'].item():.4e} | "

    msg += (
        f"IC: {losses['ic'].item():.4e} | "
        f"BC: {losses['bc'].item():.4e} | "
        f"m_phi: {losses['m_phi'].item():.6e} | "
        f"rel.err: {rel_err:.3e}"
    )

    print(msg)


def run_pretraining(
    model: nn.Module,
    log_m_phi: nn.Parameter,
    optimizer: torch.optim.Optimizer,
    data: Dict[str, Any],
    args: argparse.Namespace,
    device: torch.device,
    generator: torch.Generator,
    history: Dict[str, list],
) -> None:
    """
    Run the pretraining phase without PDE residuals.

    This phase fits observed data, initial condition and boundary condition
    before activating the source-free dynamics constraint.
    """
    if args.pretrain_epochs <= 0:
        return

    print("\n" + "=" * 40)
    print("PRETRAIN: data + IC + BC only")
    print("=" * 40)

    for epoch in range(1, args.pretrain_epochs + 1):
        model.train()

        batch = sample_batches(
            data=data,
            args=args,
            device=device,
            generator=generator,
        )

        optimizer.zero_grad()

        total, losses = evaluate_losses(
            model=model,
            log_m_phi=log_m_phi,
            batch=batch,
            data=data,
            args=args,
            use_pde=False,
        )

        total.backward()
        optimizer.step()

        append_history(history, losses, phase="pretrain")

        if epoch == 1 or epoch % args.print_every == 0:
            print_step(
                prefix="Pretrain",
                step=epoch,
                losses=losses,
                m_phi_true=data["m_phi_true"],
                include_pde=False,
            )


def run_adam_inverse_training(
    model: nn.Module,
    log_m_phi: nn.Parameter,
    optimizer: torch.optim.Optimizer,
    data: Dict[str, Any],
    args: argparse.Namespace,
    device: torch.device,
    generator: torch.Generator,
    history: Dict[str, list],
) -> None:
    """
    Run Adam inverse training with the source-free PDE residual active.
    """
    print("\n" + "=" * 40)
    print("ADAM INVERSE TRAINING")
    print("=" * 40)

    for epoch in range(1, args.epochs + 1):
        model.train()

        batch = sample_batches(
            data=data,
            args=args,
            device=device,
            generator=generator,
        )

        optimizer.zero_grad()

        total, losses = evaluate_losses(
            model=model,
            log_m_phi=log_m_phi,
            batch=batch,
            data=data,
            args=args,
            use_pde=True,
        )

        total.backward()
        optimizer.step()

        append_history(history, losses, phase="adam")

        if epoch == 1 or epoch % args.print_every == 0:
            print_step(
                prefix="Epoch",
                step=epoch,
                losses=losses,
                m_phi_true=data["m_phi_true"],
                include_pde=True,
            )


def run_lbfgs_refinement(
    model: nn.Module,
    log_m_phi: nn.Parameter,
    data: Dict[str, Any],
    args: argparse.Namespace,
    device: torch.device,
    generator: torch.Generator,
    history: Dict[str, list],
) -> None:
    """
    Optional L-BFGS refinement on one fixed stochastic batch.
    """
    if args.lbfgs_iter <= 0:
        return

    print("\n" + "=" * 40)
    print("L-BFGS REFINEMENT")
    print("=" * 40)

    fixed_batch = sample_batches(
        data=data,
        args=args,
        device=device,
        generator=generator,
    )

    lbfgs = torch.optim.LBFGS(
        list(model.parameters()) + [log_m_phi],
        lr=1.0,
        max_iter=args.lbfgs_iter,
        max_eval=args.lbfgs_iter * 2,
        history_size=50,
        tolerance_grad=1e-10,
        tolerance_change=1e-12,
        line_search_fn="strong_wolfe",
    )

    def closure() -> Tensor:
        lbfgs.zero_grad()

        total, losses = evaluate_losses(
            model=model,
            log_m_phi=log_m_phi,
            batch=fixed_batch,
            data=data,
            args=args,
            use_pde=True,
        )

        total.backward()
        append_history(history, losses, phase="lbfgs")

        return total

    lbfgs.step(closure)

    final_m_phi = float(torch.exp(log_m_phi).detach().cpu())
    print(f"L-BFGS completed | m_phi = {final_m_phi:.8e}")


# =============================================================================
# Evaluation
# =============================================================================

def evaluate_on_full_grid(
    model: nn.Module,
    data: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Evaluate the trained model on the full clean solver grid.
    """
    model.eval()

    with torch.no_grad():
        phi_pred = model(data["x_all"], data["t_all"])

    phi_true = data["phi_clean_all"]

    mse = torch.mean((phi_pred - phi_true) ** 2)
    rel_l2 = torch.linalg.norm(phi_pred - phi_true) / torch.linalg.norm(phi_true)

    n_t = len(data["t_grid"])
    n_x = len(data["x_grid"])

    phi_pred_grid = phi_pred.detach().cpu().numpy().reshape(n_t, n_x)

    return {
        "mse": float(mse.detach().cpu()),
        "rel_l2": float(rel_l2.detach().cpu()),
        "phi_pred_grid": phi_pred_grid,
    }


def build_metrics(
    final_m_phi: float,
    data: Dict[str, Any],
    eval_results: Dict[str, Any],
    args: argparse.Namespace,
) -> Dict[str, Any]:
    """
    Build the final scalar metrics dictionary.
    """
    rel_m_phi_error = abs(final_m_phi - data["m_phi_true"]) / abs(data["m_phi_true"])

    return {
        "m_phi_true": float(data["m_phi_true"]),
        "m_phi_final": float(final_m_phi),
        "m_phi_relative_error": float(rel_m_phi_error),
        "full_grid_mse_phi": float(eval_results["mse"]),
        "full_grid_relative_l2_phi": float(eval_results["rel_l2"]),
        "data_fraction": float(args.data_fraction),
        "data_noise": float(args.data_noise),
        "n_observed_data_points": int(data["n_obs"]),
        "n_total_data_points": int(data["n_total"]),
        "seed": int(args.seed),
    }


# =============================================================================
# Saving and plotting
# =============================================================================

def save_config(
    args: argparse.Namespace,
    data: Dict[str, Any],
    run_dir: Path,
) -> None:
    """
    Save the full run configuration to JSON.
    """
    config = vars(args).copy()

    config.update(
        {
            "m_phi_true": data["m_phi_true"],
            "k": data["k"],
            "eps": data["eps"],
            "t_final": data["t_final"],
            "n_total_data_points": data["n_total"],
            "n_observed_data_points": data["n_obs"],
        }
    )

    with open(run_dir / "run_config.json", "w") as f:
        json.dump(config, f, indent=4)


def save_history(history: Dict[str, list], out_path: Path) -> None:
    """
    Save optimization history to JSON.
    """
    with open(out_path, "w") as f:
        json.dump(history, f, indent=4)


def save_metrics(metrics: Dict[str, Any], out_path: Path) -> None:
    """
    Save scalar final metrics to JSON.
    """
    clean_metrics = {}

    for key, value in metrics.items():
        if isinstance(value, (float, int, str, bool)):
            clean_metrics[key] = value

    with open(out_path, "w") as f:
        json.dump(clean_metrics, f, indent=4)


def plot_losses(history: Dict[str, list], fig_dir: Path) -> None:
    """
    Plot the training loss history.
    """
    fig_dir.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 5))

    for key in ["total", "data", "pde", "ic", "bc"]:
        values = np.array(history[key], dtype=np.float64)
        values = np.maximum(values, 1e-16)
        plt.semilogy(values, label=key)

    plt.xlabel("Optimization step")
    plt.ylabel("Loss")
    plt.title("AC1D blind inverse training losses")
    plt.legend()
    plt.grid(True, which="both", linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.savefig(fig_dir / "losses.png", dpi=180)
    plt.close()


def plot_m_phi(
    history: Dict[str, list],
    data: Dict[str, Any],
    fig_dir: Path,
) -> None:
    """
    Plot the learned mobility trajectory.
    """
    plt.figure(figsize=(8, 5))

    m_values = np.array(history["m_phi"], dtype=np.float64)

    plt.plot(m_values, label=r"learned $m_\phi$")
    plt.axhline(
        data["m_phi_true"],
        linestyle="--",
        color="black",
        label=r"true $m_\phi$",
    )

    plt.xlabel("Optimization step")
    plt.ylabel(r"$m_\phi$")
    plt.title("Blind inverse inference of mobility")
    plt.legend()
    plt.grid(True, alpha=0.4)
    plt.tight_layout()
    plt.savefig(fig_dir / "m_phi_convergence.png", dpi=180)
    plt.close()


def plot_field_diagnostics(
    eval_results: Dict[str, Any],
    data: Dict[str, Any],
    fig_dir: Path,
) -> None:
    """
    Plot final-time comparison and full space-time absolute error.
    """
    x_grid = data["x_grid"]
    t_grid = data["t_grid"]

    phi_true = data["phi_grid"]
    phi_pred = eval_results["phi_pred_grid"]
    error = np.abs(phi_pred - phi_true)

    plt.figure(figsize=(7, 4.5))
    plt.plot(x_grid, phi_true[-1], label="solver data")
    plt.plot(x_grid, phi_pred[-1], "--", label="PINN")
    plt.xlabel("x")
    plt.ylabel(r"$\phi(x,T)$")
    plt.title("Final-time profile")
    plt.legend()
    plt.grid(True, alpha=0.4)
    plt.tight_layout()
    plt.savefig(fig_dir / "phi_final_comparison.png", dpi=180)
    plt.close()

    plt.figure(figsize=(7, 4.5))
    plt.imshow(
        error,
        aspect="auto",
        origin="lower",
        extent=[x_grid[0], x_grid[-1], t_grid[0], t_grid[-1]],
    )
    plt.colorbar(label=r"$|\phi_\theta-\phi_{\mathrm{data}}|$")
    plt.xlabel("x")
    plt.ylabel("t")
    plt.title("Absolute error heatmap")
    plt.tight_layout()
    plt.savefig(fig_dir / "phi_error_heatmap.png", dpi=180)
    plt.close()


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    """
    Train the source-free AC1D inverse PINN and save final artifacts.
    """
    args = parse_args()
    validate_args(args)

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    run_dir = Path(args.out_root) / args.run_name
    fig_dir = run_dir / "figures"
    weights_dir = run_dir / "weights"

    fig_dir.mkdir(parents=True, exist_ok=True)
    weights_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("AC1D SOURCE-FREE BLIND INVERSE PINN")
    print("=" * 80)
    print(f"Device      : {device}")
    print(f"Data path   : {args.data_path}")
    print(f"Run dir     : {run_dir}")
    print(f"m_phi_init  : {args.m_phi_init}")
    print("=" * 80)

    data = load_ac1d_data(args=args, device=device)

    print("Loaded data:")
    print(f"  m_phi_true        = {data['m_phi_true']:.6f}")
    print(f"  k                 = {data['k']:.6f}")
    print(f"  eps               = {data['eps']:.6f}")
    print(f"  T_final           = {data['t_final']:.6f}")
    print(f"  total data points = {data['n_total']}")
    print(f"  observed points   = {data['n_obs']}")
    print(f"  data_fraction     = {args.data_fraction}")
    print(f"  data_noise        = {args.data_noise}")
    print("=" * 80)

    save_config(
        args=args,
        data=data,
        run_dir=run_dir,
    )

    model, log_m_phi, optimizer = initialize_model_and_optimizer(
        args=args,
        device=device,
    )

    generator = torch.Generator(device=device)
    generator.manual_seed(args.seed + 2000)

    history = init_history()

    run_pretraining(
        model=model,
        log_m_phi=log_m_phi,
        optimizer=optimizer,
        data=data,
        args=args,
        device=device,
        generator=generator,
        history=history,
    )

    run_adam_inverse_training(
        model=model,
        log_m_phi=log_m_phi,
        optimizer=optimizer,
        data=data,
        args=args,
        device=device,
        generator=generator,
        history=history,
    )

    run_lbfgs_refinement(
        model=model,
        log_m_phi=log_m_phi,
        data=data,
        args=args,
        device=device,
        generator=generator,
        history=history,
    )

    torch.save(model.state_dict(), weights_dir / "model.pt")

    final_m_phi = float(torch.exp(log_m_phi).detach().cpu())

    eval_results = evaluate_on_full_grid(
        model=model,
        data=data,
    )

    metrics = build_metrics(
        final_m_phi=final_m_phi,
        data=data,
        eval_results=eval_results,
        args=args,
    )

    save_metrics(metrics, run_dir / "metrics.json")
    save_history(history, run_dir / "history.json")

    plot_losses(history, fig_dir)
    plot_m_phi(history, data, fig_dir)
    plot_field_diagnostics(eval_results, data, fig_dir)

    print("\n" + "=" * 80)
    print("FINAL RESULTS")
    print("=" * 80)
    print(f"m_phi_true             : {metrics['m_phi_true']:.8e}")
    print(f"m_phi_final            : {metrics['m_phi_final']:.8e}")
    print(f"m_phi_relative_error   : {metrics['m_phi_relative_error']:.8e}")
    print(f"full_grid_mse_phi      : {metrics['full_grid_mse_phi']:.8e}")
    print(f"full_grid_rel_l2_phi   : {metrics['full_grid_relative_l2_phi']:.8e}")
    print(f"Saved run to           : {run_dir}")
    print("=" * 80)


if __name__ == "__main__":
    main()